[package]
name = "common-metrics"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }
common-infallible = { path = "../infallible" }
common-tracing = { path = "../tracing" }

# Crates.io dependencies
lazy_static = "1.4.0"
metrics = "0.17.0"
metrics-exporter-prometheus = "0.6.0"
prometheus-parse = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
