[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[features]
default = ["arrow-default", "parquet-default"]
arrow-default = ["arrow/compute", "arrow/regex", "arrow/merge_sort", "arrow/io_csv", "arrow/io_parquet", "arrow/io_json", "arrow/io_flight"]
parquet-default = ["parquet2/stream", "parquet2/lz4"]
simd = ["arrow/simd"]

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies
arrow = { package = "arrow2", git="https://github.com/datafuse-extras/arrow2", default-features = false, rev = "bd8f02b" }
arrow-format = { version = "0.2.1", features = ["flight-data", "flight-service"]}
parquet2 = { version = "0.6", default_features = false }
# Crates.io dependencies

[dev-dependencies]
