ignore-not-existing: true
output-type: lcov
output-path: ./lcov.info
ignore:
  - "*/lib.rs"
  - "*/bin/*"
  - "*/servers/*"
  - "*/sessions/*"
  - "*/metrics/*"
  - "*/exception/*"
  - "*/tests/*"
  - "*/arrow/*"
  - "*/base/*"
  - "*/building/*"
  - "*/tracing/*"
  - "*/api/http/debug/*"
  - "cli/*"
  - "target/*"
