name: Binary Size Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-buildcache-${{ secrets.CACHE_RESET_KEY }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-buildcache-${{ secrets.CACHE_RESET_KEY }}-
            ${{ runner.os }}-cargo-buildcache-
            ${{ runner.os }}-cargo-

      - name: Run cargo bloat for databend-query
        uses: orf/cargo-bloat-action@v1
        with:
          bloat_args: --bin databend-query
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo bloat for databend-meta
        uses: orf/cargo-bloat-action@v1
        with:
          bloat_args: --bin databend-meta
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo bloat for databend-cli
        uses: orf/cargo-bloat-action@v1
        with:
          bloat_args: --bin databend-cli
          token: ${{ secrets.GITHUB_TOKEN }}
