name: Stateless(Standalone)
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Tests"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          # Linux
          - { os: ubuntu-latest, toolchain: stable, target: x86_64-unknown-linux-gnu, cross: false }
          # Macos
          - { os: macos-latest, toolchain: stable, target: x86_64-apple-darwin, cross: false }
    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh -o -t
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-buildcache-${{ secrets.CACHE_RESET_KEY }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-buildcache-${{ secrets.CACHE_RESET_KEY }}-
            ${{ runner.os }}-cargo-buildcache-
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --verbose
        env:
          CARGO_INCREMENTAL: '0'

      - name: Minio Setup for (ubuntu-latest only)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          docker run -d -p 9000:9000 --name minio \
                  -e "MINIO_ACCESS_KEY=minioadmin" \
                  -e "MINIO_SECRET_KEY=minioadmin" \
                  -v /tmp/data:/data \
                  -v /tmp/config:/root/.minio \
                  minio/minio server /data

          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_EC2_METADATA_DISABLED=true

          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://testbucket

      - name: Run Stateless Tests with Standalone mode (ubuntu-latest only)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          bash ./scripts/ci/ci-run-stateless-tests-standalone-s3.sh

      - name: Run Stateless Tests with Standalone mode
        if: matrix.config.os != 'ubuntu-latest'
        run: |
          bash ./scripts/ci/ci-run-stateless-tests-standalone.sh
